### ISSUE TITLE
[BUG] Mutation is possible on nested fields

### ISSUE THREAD

**Issue by agates4** [Marco-Sulla/python-frozendict#31]
OS version: OS X 11.5.2, ARM M1

Python3 version (python3 -V -V):
```
Python 3.7.9 (default, Dec 18 2020, 05:32:43) 
[GCC 8.3.0]
```

Steps to reproduce:

1. open up a python shell
```
>>> from frozendict import frozendict
>>> frozen = frozendict({"outer": "outer", "inner": {"test": "can mutate"}})
>>> frozen
frozendict({'outer': 'outer', 'inner': {'test': 'can mutate'}})

>>> frozen['outer'] = 'uhoh'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/frozendict/core.py", line 146, in __setitem__
    f"'{self.__class__.__name__}' object doesn't support item "
TypeError: 'frozendict' object doesn't support item assignment
# nice, we can't mutate top level fields

>>> frozen['inner']['test'] = 'i totally did just mutate that'
>>> frozen
frozendict({'outer': 'outer', 'inner': {'test': 'i totally did just mutate that'}})
# damn, we can mutate any nested fields
```

For what it's worth, `MappingProxyType` has the same problem.
Should I be recursively serializing each field as a frozendict?

**Comment by agates4** [comment]
I wrote a quick recursive method here to serialize all inner dict members
```
from frozendict import frozendict

test_data = {'outer': 'outer', 'inner': {'test': {'oop': 'pretty far'}, 'test2': 'ooop', 'test3': {'ooop': {'oopoop': 'OPE!'}}}}

def serialize_as_frozendict(data):
    for key, value in data.items():
        if isinstance(value, dict):
            data[key] = serialize_as_frozendict(value)
    return frozendict(data)

print(serialize_as_frozendict(test_data))
```

results in
```
frozendict({'outer': 'outer', 'inner': frozendict({'test': frozendict({'oop': 'pretty far'}), 'test2': 'ooop', 'test3': frozendict({'ooop': frozendict({'oopoop': 'OPE!'})})})})
```

for what it's worth, maybe we don't want to default serialize recursively. but, as a feature request, I'd like to see an option for it.

**Comment by Marco-Sulla** [comment]
See #30
