### ISSUE TITLE
[BUG] Python 3.10+ compat

### ISSUE THREAD

**Issue by oberstet** [Marco-Sulla/python-frozendict#44]
`Mapping` was moved to `collections.abc`

```
(cpy39_1) (base) oberstet@intel-nuci7:~/myproject$ python -c "from collections import Mapping"
<string>:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
(cpy39_1) (base) oberstet@intel-nuci7:~/myproject$ python -V
Python 3.9.4
```

and consequently the library import fails

```
(cpy310_2) (base) oberstet@intel-nuci7:~/myproject$ python -c "from frozendict import frozendict"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/oberstet/cpy310_2/lib/python3.10/site-packages/frozendict/__init__.py", line 16, in <module>
    class frozendict(collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
(cpy310_2) (base) oberstet@intel-nuci7:~/myproject$ python -V
Python 3.10.0
(cpy310_2) (base) oberstet@intel-nuci7:~/myproject$ pip show frozendict
Name: frozendict
Version: 1.2
Summary: An immutable dictionary
Home-page: https://github.com/slezica/python-frozendict
Author: Santiago Lezica
Author-email: slezica89@gmail.com
License: MIT License
Location: /home/oberstet/cpy310_2/lib/python3.10/site-packages
Requires: 
Required-by: cairo-lang

```

**Comment by oberstet** [comment]
ahh, sorry: the version I was using wasn't the current one - which does work ok! false alarm

```
(cpy310_2) (base) oberstet@intel-nuci7:~/myproject$ python -c "from frozendict import frozendict"
(cpy310_2) (base) oberstet@intel-nuci7:~/myproject$ pip show frozendict
Name: frozendict
Version: 2.1.3
Summary: A simple immutable dictionary
Home-page: https://github.com/Marco-Sulla/python-frozendict
Author: Marco Sulla
Author-email: marcosullaroma@gmail.com
License: LGPL v3
Location: /home/oberstet/cpy310_2/lib/python3.10/site-packages
Requires: 
Required-by: cairo-lang
```

**Comment by Marco-Sulla** [comment]
You can signal any problem here:
https://github.com/Marco-Sulla/python-frozendict
