### ISSUE TITLE
[ENHANCEMENT] Not usable with pyinstaller

### ISSUE THREAD

**Issue by AdrienPensart** [Marco-Sulla/python-frozendict#64]
Hello!

It seems this library is not compatible with pyinstaller, for one reason : there is this VERSION file in the package itself.

In my opinion, the version should be stored in a .py file, because VERSION is not taken into account during pyinstaller build.

```
Traceback (most recent call last):
  File "run_cli_unity/main.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "run_cli_unity/cloud/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "run_cli_unity/cloud/entities/aggregate.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "run_cli_unity/cloud/host_filter.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "run_cli_unity/cloud/object.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "frozendict/__init__.py", line 33, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIqLoUjT/frozendict/VERSION'
[2247] Failed to execute script 'main' due to unhandled exception!
```

**Comment by Marco-Sulla** [comment]
Fixed in https://github.com/Marco-Sulla/python-frozendict/commit/cec2f093bcac9c6a894d988c51bc2f4af1ee22d7

I'll do a new release when I'll change or add something more important. In the meanwhile, can't you use some config to include also the VERSION file?

**Comment by AdrienPensart** [comment]
Yes there is a way to include it manually in pyinstaller bit it remains a trick. Thank you!

**Comment by Marco-Sulla** [comment]
It should be fixed with the new release:
https://github.com/Marco-Sulla/python-frozendict/releases/tag/v2.3.5

Can you confirm it?

**Comment by Marco-Sulla** [comment]
Closing, feel free to reopen if the issue happens again.
